/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td2.app;

import td2.list.LinkedList;

import static td2.utilities.StringUtils.join;
import static td2.utilities.StringUtils.split;
import static td2.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
